# Generated by Django 5.2.8 on 2025-11-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('daily_kcal', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'template',
            },
        ),
        migrations.CreateModel(
            name='TemplateIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_day', models.IntegerField()),
                ('intake_alias', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'template_intake',
            },
        ),
    ]
