# Generated by Django 5.2.8 on 2025-11-14 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dishes', '0002_initial'),
        ('Intakes', '0001_initial'),
        ('Plantillas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateintake',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dishes.dish'),
        ),
        migrations.AddField(
            model_name='templateintake',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intakes.intake'),
        ),
        migrations.AddField(
            model_name='templateintake',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantillas.template'),
        ),
        migrations.AddField(
            model_name='template',
            name='intake',
            field=models.ManyToManyField(through='Plantillas.TemplateIntake', to='Intakes.intake'),
        ),
    ]
