# Generated by Django 5.2.8 on 2026-07-28 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantillas', '0002_initial'),
        ('SuperGroup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('max', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('frequency', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('super_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='SuperGroup.supergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rules',
                'ordering': ['level', 'super_group__name', 'id'],
                'indexes': [models.Index(fields=['user'], name='rules_user_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('min__lte', models.F('max'))), name='rules_min_lte_max')],
            },
        ),
    ]
