# Generated by Django 5.2.8 on 2026-07-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantillas', '0003_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
