# Generated by Django 5.2.8 on 2026-07-28 19:19

from django.db import migrations, models


def normalize_existing_frequencies(apps, schema_editor):
    rule_model = apps.get_model('Plantillas', 'Rule')
    rule_model.objects.using(schema_editor.connection.alias).exclude(
        frequency__in=('daily', 'weekly'),
    ).update(frequency='daily')


class Migration(migrations.Migration):

    dependencies = [
        ('Plantillas', '0004_rule_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal')], max_length=10),
        ),
        migrations.RunPython(
            normalize_existing_frequencies,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
