# Generated by Django 5.2.8 on 2026-09-22 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0008_dishcategory_dish_dish_category_dishcategorysize_and_more'),
        ('Plantillas', '0005_alter_rule_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='templateintake',
            name='is_free_meal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='templateintake',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dishes.dish'),
        ),
    ]
