# Generated by Django 5.2.8 on 2025-11-14 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dishes', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
        migrations.AddField(
            model_name='dish',
            name='product',
            field=models.ManyToManyField(through='Dishes.DishProduct', to='Products.product'),
        ),
    ]
