# Generated by Django 5.2.8 on 2026-07-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0002_initial'),
        ('Intakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='intakes',
            field=models.ManyToManyField(blank=True, to='Intakes.intake'),
        ),
    ]
