# Generated by Django 5.2.8 on 2026-07-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0003_dish_active_dish_intakes'),
        ('Intakes', '0002_intake_ingesta_intake_order_points_intake_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dishes.dish')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intakes.intake')),
            ],
            options={
                'db_table': 'dish_intake',
            },
        ),
    ]
