# Generated by Django 5.2.8 on 2026-08-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0004_dishintake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DishIntake',
        ),
    ]
