# Generated by Django 5.2.8 on 2026-08-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0005_delete_dishintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(choices=[('entrante', 'Entrante'), ('principal', 'Plato principal'), ('postre', 'Postre'), ('unico', 'Plato único')], default='principal', max_length=10),
        ),
    ]
