# Generated by Django 5.2.8 on 2026-08-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0007_dish_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('name_es', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255)),
                ('name_el', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'dish_type',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='Dishes.dishcategory'),
        ),
        migrations.CreateModel(
            name='DishCategorySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=6)),
                ('dish_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='Dishes.dishcategory')),
            ],
            options={
                'db_table': 'dish_type_size',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_category_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='Dishes.dishcategorysize'),
        ),
    ]
