# Generated by Django 5.2.8 on 2025-11-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('height', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dni', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=12)),
                ('phone_number_2', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('activity_level', models.CharField(choices=[('Reposo', 'Reposo'), ('Ligera', 'Ligera'), ('Moderada', 'Moderada'), ('Intensa', 'Intensa')], max_length=20)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
