# Generated by Django 5.2.8 on 2026-07-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
