# Generated by Django 5.2.8 on 2026-08-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_client_gasto_energetico_client_imc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMeasurementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metabolismo_basal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('gasto_energetico', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_history', to='Clients.client')),
            ],
            options={
                'db_table': 'client_measurement_history',
                'ordering': ['-updated_at'],
            },
        ),
    ]
