# Generated by Django 5.2.8 on 2026-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='ingesta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='intake',
            name='order_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intake',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
