# Generated by Django 5.2.8 on 2026-07-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intakes', '0002_intake_ingesta_intake_order_points_intake_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='order_points',
            field=models.IntegerField(default='0'),
        ),
    ]
