# Generated by Django 5.2.8 on 2026-07-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intakes', '0003_alter_intake_order_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='order_points',
            field=models.IntegerField(default=0),
        ),
    ]
