# Generated by Django 5.2.8 on 2026-08-12 23:42

from django.db import migrations, models

# Mapeo de las tomas semilla (Intakes/migrations/0005_add_default_intakes.py)
# a su rol dentro de una comida/cena (entrante/principal/postre) y al grupo
# ('comida'/'cena') al que pertenecen, para que el generador de dietas sepa
# qué Intake usar para cada curso.
COURSE_ROLE_BY_NAME = {
    'Desayuno': ('single', ''),
    'Media mañana': ('single', ''),
    '1ª plato Comida': ('starter', 'comida'),
    'Plato principal comida': ('main', 'comida'),
    'Postre': ('dessert', ''),
    'Merienda': ('single', ''),
    '1ª plato Cena': ('starter', 'cena'),
    'Plato principal cena': ('main', 'cena'),
    'Recena': ('single', ''),
    'Otros': ('single', ''),
}


def set_course_roles(apps, schema_editor):
    Intake = apps.get_model('Intakes', 'Intake')
    for name, (course_role, meal_group) in COURSE_ROLE_BY_NAME.items():
        Intake.objects.filter(name=name).update(course_role=course_role, meal_group=meal_group)


def unset_course_roles(apps, schema_editor):
    Intake = apps.get_model('Intakes', 'Intake')
    Intake.objects.filter(name__in=COURSE_ROLE_BY_NAME.keys()).update(course_role='single', meal_group='')


class Migration(migrations.Migration):

    dependencies = [
        ('Intakes', '0005_add_default_intakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='course_role',
            field=models.CharField(choices=[('single', 'Único'), ('starter', 'Entrante'), ('main', 'Principal'), ('dessert', 'Postre')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='intake',
            name='meal_group',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(set_course_roles, unset_course_roles),
    ]
