"""
Django settings for idiet project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En produccion, define DJANGO_SECRET_KEY como variable de entorno; el valor
# por defecto solo es apto para desarrollo local.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-!z65&q--jd5pz7h&f6e&=c!)wya*3+yb!%c^tzx23fg&sv4o5r',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Allergens',
    'Appointments',
    'Clients',
    'Dishes',
    'FoodGroup',
    'SuperGroup',
    'Intakes',
    'Menus',
    'Micronutrients',
    'Plantillas',
    'Products',
    'Users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'idiet.middleware.DatabaseEnvironmentMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'idiet.urls'

LOGIN_URL = '/login/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = 'Users.User'

WSGI_APPLICATION = 'idiet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('IDIET_DATABASE_NAME', 'idiet_django'),
        'USER': os.environ.get('IDIET_DATABASE_USER', 'root'),
        'PASSWORD': os.environ.get('IDIET_DATABASE_PASSWORD', 'root'),
        'HOST': os.environ.get('IDIET_DATABASE_HOST', 'localhost'),
        'PORT': os.environ.get('IDIET_DATABASE_PORT', '3306'),
    },
    'training': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('IDIET_TRAINING_DATABASE_NAME', 'idiet_django_formacion'),
        'USER': os.environ.get('IDIET_TRAINING_DATABASE_USER', os.environ.get('IDIET_DATABASE_USER', 'root')),
        'PASSWORD': os.environ.get('IDIET_TRAINING_DATABASE_PASSWORD', os.environ.get('IDIET_DATABASE_PASSWORD', 'root')),
        'HOST': os.environ.get('IDIET_TRAINING_DATABASE_HOST', os.environ.get('IDIET_DATABASE_HOST', 'localhost')),
        'PORT': os.environ.get('IDIET_TRAINING_DATABASE_PORT', os.environ.get('IDIET_DATABASE_PORT', '3306')),
    },
}

DATABASE_ROUTERS = ['idiet.db_router.EnvironmentDatabaseRouter']

# Permite conocer la base elegida antes de consultar al usuario autenticado.
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'


# Email (recuperacion de contrasena)
# Por defecto se usa el backend de consola (los correos se imprimen en la
# terminal en vez de enviarse). Para activar el envio real, define
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend y las
# credenciales EMAIL_* en el .env.
PASSWORD_RESET_TIMEOUT = 1800  # 30 minutos

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@idiet.local')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
