# Generated by Django 5.2.8 on 2026-04-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='motive',
            field=models.CharField(default='Consulta inicial', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada')], default='Pendiente', max_length=20),
        ),
    ]
