# Generated by Django 5.2.8 on 2026-08-05 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_alter_client_address'),
        ('FoodGroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroupExcluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_food_groups', to='Clients.client')),
                ('food_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodGroup.foodgroup')),
            ],
            options={
                'db_table': 'food_group_excluded',
                'unique_together': {('client', 'food_group')},
            },
        ),
    ]
