# Generated by Django 5.2.8 on 2026-04-28 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dishes', '0002_initial'),
        ('Intakes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ini', models.DateField()),
                ('date_fin', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='MenuIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_day', models.IntegerField()),
                ('intake_alias', models.CharField(max_length=200)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dishes.dish')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intakes.intake')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menus.menu')),
            ],
            options={
                'db_table': 'menu_intake',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='intake',
            field=models.ManyToManyField(through='Menus.MenuIntake', to='Intakes.intake'),
        ),
    ]
