# Generated by Django 5.2.8 on 2026-08-12 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_clientmeasurementhistory'),
        ('Menus', '0002_fix_menu_table_collision'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='Clients.client'),
        ),
    ]
