# Generated by Django 5.2.8 on 2026-08-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0003_menu_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='generation_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
