# Generated by Django 5.2.8 on 2026-09-03 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0008_dishcategory_dish_dish_category_dishcategorysize_and_more'),
        ('Menus', '0004_menu_generation_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuintake',
            name='is_free_meal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuintake',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dishes.dish'),
        ),
    ]
