# Generated by Django 5.2.8 on 2025-11-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Micronutrients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='Original food name. Must be less than 200 characters', max_length=200)),
                ('food_name_spanish', models.CharField(max_length=200)),
                ('food_name_eng', models.CharField(max_length=200)),
                ('origin_db', models.CharField(max_length=50)),
                ('ed_porc', models.IntegerField()),
                ('kcal_100g', models.IntegerField()),
                ('prot_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ch_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('micronutrient', models.ManyToManyField(to='Micronutrients.micronutrient')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
