# Generated by Django 5.2.8 on 2026-04-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodGroup', '0001_initial'),
        ('Micronutrients', '0001_initial'),
        ('Products', '0001_initial'),
        ('SuperGroup', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='product',
                    name='micronutrient',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='product',
            name='food_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodGroup.foodgroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='super_groups',
            field=models.ManyToManyField(blank=True, to='SuperGroup.supergroup'),
        ),
        migrations.CreateModel(
            name='ProductMicronutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('micronutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Micronutrients.micronutrient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
            options={
                'db_table': 'product_micronutrient',
                'unique_together': {('product', 'micronutrient')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='micronutrients',
            field=models.ManyToManyField(through='Products.ProductMicronutrient', to='Micronutrients.micronutrient'),
        ),
    ]
