# Generated by Django 5.2.8 on 2026-08-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_product_user'),
        ('Products', '0005_productexcluded_client'),
    ]

    operations = [
    ]
